language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install --upgrade pip setuptools wheel
  - pip install coveralls

script:
  - coverage run --source=researchutils setup.py test

after_success:
  - coveralls